version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      # - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - keycloak-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    command:
      - start-dev
      - --import-realm
      # - --features=declarative-user-profile
    ports:
      - "8180:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      # KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./stereocean-keycloak-theme/dist_keycloak/target/keycloakify-starter-keycloak-theme-6.1.10.jar:/opt/keycloak/providers/keycloakify-starter-keycloak-theme-6.1.10.jar
      - ./stereocean-keycloak-theme/dist_keycloak/src/main/resources/theme/account-v1:/opt/keycloak/themes/account-v1
      - ./stereocean-keycloak-theme/dist_keycloak/src/main/resources/theme/keycloakify-starter:/opt/keycloak/themes/keycloakify-starter
      - ./stereocean-keycloak-theme/dist_keycloak/src/main/resources/theme/keycloakify-starter_retrocompat:/opt/keycloak/themes/keycloakify-starter_retrocompat
    networks:
      - keycloak-network
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
volumes:
  postgres_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
